[project]
name = "flipdoc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Om Rajput", email = "omrajputt369@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pymupdf>=1.28.2",
    "typer>=0.27.2",
]

[project.scripts]
flipdoc = "flipdoc:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
